/*
 * generated by Xtext 2.10.0
 */
package arden.plugin.editor.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;
import org.eclipse.xtext.ide.editor.syntaxcoloring.ISemanticHighlightingCalculator;
import org.eclipse.xtext.ui.editor.folding.IFoldingRegionProvider;
import org.eclipse.xtext.ui.editor.syntaxcoloring.AbstractAntlrTokenToAttributeIdMapper;
import org.eclipse.xtext.ui.editor.syntaxcoloring.IHighlightingConfiguration;
<<<<<<< HEAD
=======
import org.eclipse.xtext.ui.editor.templates.XtextTemplateContextType;
import org.eclipse.xtext.ui.wizard.IProjectCreator;
>>>>>>> 72d50c0... Fix wizard

import arden.plugin.editor.ui.folding.ArdenSyntaxFoldingRegionProvider;
import arden.plugin.editor.ui.syntaxcoloring.ArdenSyntaxAntlrTokenToAttributeIdMapper;
import arden.plugin.editor.ui.syntaxcoloring.ArdenSyntaxHighlightingConfiguration;
import arden.plugin.editor.ui.syntaxcoloring.ArdenSyntaxSemanticHighlightingCalculator;
<<<<<<< HEAD
=======
import arden.plugin.editor.ui.templates.ArdenSyntaxTemplateContextType;
import arden.plugin.editor.ui.wizard.ArdenSyntaxProjectCreator;
>>>>>>> 72d50c0... Fix wizard

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
public class ArdenSyntaxUiModule extends AbstractArdenSyntaxUiModule {

	public ArdenSyntaxUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
	
    public Class<? extends ISemanticHighlightingCalculator> bindISemanticHighlightingCalculator() {
        return ArdenSyntaxSemanticHighlightingCalculator.class;
    }

    public Class<? extends IHighlightingConfiguration> bindIHighlightingConfiguration() {
        return ArdenSyntaxHighlightingConfiguration.class;
    }

    public Class<? extends IFoldingRegionProvider> bindIFoldingRegionProvider() {
        return ArdenSyntaxFoldingRegionProvider.class;
    }
    
    public Class<? extends AbstractAntlrTokenToAttributeIdMapper> bindAbstractAntlrTokenToAttributeIdMapper() {
    	return ArdenSyntaxAntlrTokenToAttributeIdMapper.class ;
    }
    
	public Class<? extends IProjectCreator> bindIProjectCreator() {
		return ArdenSyntaxProjectCreator.class;
	}
}
