/*
* generated by Xtext
*/
package arden.plugin.editor.ui.contentassist;

import java.util.Arrays;
import java.util.HashSet;
import java.util.Set;

import org.eclipse.xtext.Keyword;
import org.eclipse.xtext.ui.editor.contentassist.ContentAssistContext;
import org.eclipse.xtext.ui.editor.contentassist.ICompletionProposalAcceptor;

/**
 * see http://www.eclipse.org/Xtext/documentation/latest/xtext.html#contentAssist on how to customize content assistant
 */
public class ArdenSyntaxProposalProvider extends AbstractArdenSyntaxProposalProvider {
    
    // no content assist for keywords which are already handled by templates
    private static Set<String> FILTERED_KEYWORDS = new HashSet<String>(Arrays.asList(
            "mlmname:",
            "filename:",
            "arden:",
            "version:",
            "date:",
            "validation:",
            "type:",
            "priority:",
            "urgency:",
            "data:",
            "evoke:",
            "logic:",
            "action:",
            "maintenance:",
            "library:",
            "knowledge:"
    ));
    
    @Override
    public void completeKeyword(Keyword keyword, ContentAssistContext contentAssistContext, ICompletionProposalAcceptor acceptor) {
        if (FILTERED_KEYWORDS.contains(keyword.getValue())) {
            // don't propose keyword
            return;
        }
        super.completeKeyword(keyword, contentAssistContext, acceptor);
    }
}
