/*
 * generated by Xtext 2.10.0
 */
package arden.plugin.editor;


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
public class ArdenSyntaxStandaloneSetup extends ArdenSyntaxStandaloneSetupGenerated {

	public static void doSetup() {
		new ArdenSyntaxStandaloneSetup().createInjectorAndDoEMFRegistration();
	}				
}
