/*
 * generated by Xtext 2.10.0
 */
package arden.plugin.editor;

import org.eclipse.xtext.conversion.IValueConverterService;
import org.eclipse.xtext.linking.impl.LinkingDiagnosticMessageProvider;
import org.eclipse.xtext.parser.antlr.ISyntaxErrorMessageProvider;

import arden.plugin.editor.converter.ArdenSyntaxValueConverter;
import arden.plugin.editor.validation.ArdenSyntaxLinkingDiagnosticMessageProvider;
import arden.plugin.editor.validation.ArdenSyntaxSyntaxErrorMessageProvider;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class ArdenSyntaxRuntimeModule extends AbstractArdenSyntaxRuntimeModule {
    public Class<? extends ISyntaxErrorMessageProvider> bindISyntaxErrorMessageProvider() {
        return ArdenSyntaxSyntaxErrorMessageProvider.class;
    }
    @Override
    public Class<? extends IValueConverterService> bindIValueConverterService() {
        return ArdenSyntaxValueConverter.class;
    }
    
    public Class<? extends LinkingDiagnosticMessageProvider> bindLinkingDiagnosticMessageProvider() {
        return ArdenSyntaxLinkingDiagnosticMessageProvider.class;
    }
    
}
