/*
 * generated by Xtext 2.10.0
 */
package arden.plugin.editor.tests

import arden.plugin.editor.ardenSyntax.mlms
import com.google.inject.Inject
import org.eclipse.xtext.junit4.InjectWith
import org.eclipse.xtext.junit4.XtextRunner
import org.eclipse.xtext.junit4.util.ParseHelper
import org.junit.Assert
import org.junit.Test
import org.junit.runner.RunWith

@RunWith(XtextRunner)
@InjectWith(ArdenSyntaxInjectorProvider)
class ArdenSyntaxParsingTest{

	@Inject
	ParseHelper<mlms> parseHelper

	@Test 
	def void loadModel() {
		val result = parseHelper.parse('''
			Hello Xtext!
		''')
		Assert.assertNotNull(result)
	}

}
