/*
 * generated by Xtext 2.10.0
 */
package arden.plugin.editor.tests

import arden.plugin.editor.tests.specification.SpecificationTestSuite
import org.junit.runner.RunWith
import org.junit.runners.Suite
import org.junit.runners.Suite.SuiteClasses

@RunWith(Suite)
@SuiteClasses(SpecificationTestSuite)
class ArdenSyntaxParsingTest {
    // this file is regenerated when deleted, so delegate to the specification test suite for now
}
