/*
 * generated by Xtext 2.10.0
 */
package arden.plugin.editor.scoping;


/**
 * This class contains custom scoping description.
 * 
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#scoping
 * on how and when to use it.
 */
public class ArdenSyntaxScopeProvider extends AbstractArdenSyntaxScopeProvider {

}
